import {Dimensions} from "react-native";

export const WIDTH = Dimensions.get('window').width;
export const HEIGHT = Dimensions.get('window').height;
export const MARGINS = 12;
export const PADDING = 28;
export const PRIMARY_DARK = '#00695C';
export const PRIMARY = '#00897B';
export const PRIMARY_LIGHT = '#26A69A';
export const PRIMARY_VERY_LIGHT = '#80CBC4';
export const SECONDARY = '#F4511E';
export const SECONDARY_LIGHT = '#FF7043';
export const TEXT = '#000000';
export const BACKGROUND = '#FFFFFF';
export const NEUTRAL = '#BDBDBD';
export const BASE_URL = 'http://127.0.0.1:5196/';
export const TOAST_OFFSET = 50;
export const CALENDAR_TOP_POSITION = 80;
export const TAG_WIDTH = WIDTH * 0.55;
export const RED = '#B00020';
